---

- name: "Ensure stow is installed"
  community.general.homebrew:
    name: stow
    state: present
  tags: homebrew

- name: "Stow dotfiles"
  ansible.builtin.command:
    cmd: stow {{ item }}
    chdir: "{{ playbook_dir }}/../../.."
  with_items: "{{ dotfiles.stow_packages }}"
  when: dotfiles.stow_packages is defined
  register: stow_result
  failed_when: 
    - stow_result.rc != 0
    - '"can not fold with existing file" not in stow_result.stderr'
