# Packages for linux.
# I'm not using these, but keeping it as an example
#
# packages:
#   - build-essential
#   - libssl-dev
#   - llvm
#   - python3-pip
#   - python-is-python3
#   - vim
#   - less
brew:
  taps:
    - homebrew/bundle
    - homebrew/services
    - koekeishiya/formulae
    - libsql/sqld
    - localstack/tap
    - oven-sh/bun
    - stripe/stripe-cli
    - tursodatabase/tap
    - aws/tap
    - hashicorp/tap

  casks:
    - 1password
    - alacritty
    - arc
    - audio-hijack
    - cursor
    - discord
    - font-fira-code-nerd-font
    - font-hack-nerd-font
    - font-monaspace-nerd-font
    - font-noto-sans-symbols-2
    - font-powerline-symbols
    - google-chrome
    - homerow
    - insomnia
    - karabiner-elements
    - linear-linear
    - loopback
    - obsidian
    - orbstack
    - raycast
    - responsively
    - rocket
    - setapp
    - slack
    - spotify
    - telegram
    - typefully
    - yaak
    - visual-studio-code
    - wakatime
    - wezterm
    - whatsapp
    - aws-vpn-client
    - figma
    - ngrok

  packages:
    common:
      - ansible
      - awscli
      - bash
      - bat
      - bc
      - caddy
      - cargo-c
      - cmake
      - cmatrix
      - coreutils
      - curl
      - duf
      - elixir
      - emscripten
      - exercism
      - eza
      - fd
      - feh
      - fnm
      - fzf
      - gawk
      - gh
      - git-delta
      - glab
      - gleam
      - gnu-sed
      - gnupg
      - go
      - graphviz
      - jq
      - lazygit
      - nowplaying-cli
      - pass
      - plantuml
      - pnpm
      - python@3.11
      - ripgrep
      - starship
      - stow
      - telnet
      - terraform
      - tmux
      - wget
      - yarn
      - zoxide
      - act
      - commitizen
      - deno
      - docker-compose
      - httpie
      - vercel-cli
      - aws-cdk
      - aws-sam-cli
      - aws-vault
      - postgresql@14
      - redis
      - k6
      - mkcert
      - watchman
      - neovim
    darwin:
      - koekeishiya/formulae/skhd
      - koekeishiya/formulae/yabai
      - oven-sh/bun/bun
      - stripe/stripe-cli/stripe
      - tursodatabase/tap/turso
    linux: []

  packages_from_source:
    - duf

dotfiles:
  repo: "your-dotfiles-repo-url"
  branch: "main"
  stow_packages:
    - git
    - lazyvim
    - lvim
    - starship
    - tmux
    - wezterm
    - window-management
    - zsh

# neovim:
#   build_from_source: false
#   directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
#   build_dependencies:
#     - autoconf
#     - automake
#     - cmake
#     - curl
#     - doxygen
#     - g++
#     - gettext
#     - libtool
#     - libtool-bin
#     - ninja-build
#     - pkg-config
#     - unzip

golang:
  path: "{{ ansible_user_dir }}/.go"
  packages:
    - golang.org/x/tools/gopls@latest

nodejs:
  packages:
    - yarn
    - pnpm
    - typescript
    - ts-node
    - create-next-app
    - eslint
    - prettier
    - npm-check-updates
    - tsx
    - turbo
    - vercel
    - vite

dockitems_disabled:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - Terminal
  - iBooks
  - iTunes

dockitems_enabled:
  - name: Arc
    path: "/Applications/Arc.app"
    pos: 1
  - name: Obsidian
    path: "/Applications/Obsidian.app"
    pos: 2
  - name: Wezterm
    path: "/Applications/Wezterm.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: Whatsapp
    path: "/Applications/Whatsapp.app"
    pos: 5
  - name: Discord
    path: "/Applications/Discord.app"
    pos: 6
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 7

darwin_hotkeys:
  # remap "show spotlight search` to `⌘ + g`
  64:
    parameters: "103, 5, 1048576"
    enabled: 1
  # disable "select the previous source in input menu"
  60:
    parameters: "32, 49, 262144"
    enabled: 0
  # remap "select the next source in input menu" to `⌘ + space`
  61:
    parameters: "32, 49, 1048576"
    enabled: 1
