# Packages for linux.
# I'm not using these, but keeping it as an example
#
# packages:
#   - build-essential
#   - libssl-dev
#   - llvm
#   - python3-pip
#   - python-is-python3
#   - vim
#   - less
brew:
  casks:
    - 1password
    - alacritty
    - discord
    - docker
    - font-hack-nerd-font
    - iterm2
    - karabiner-elements
    - neovide
    - obsidian
    - raycast
    - rocket
    - slack
    - spotify
    - telegram
    - visual-studio-code
    - whatsapp
  packages:
    common:
      - cargo-c
      - cmake
      - cmatrix
      - fd
      - fzf
      - gh
      - go
      - lazygit
      - neovim
      - nvm
      - openssl
      - pnpm
      - python
      - ripgrep
      - stow
      - terraform
      - tmux
      - wget
      - yarn
      - zoxide
    darwin:
      - koekeishiya/formulae/skhd
      - koekeishiya/formulae/yabai
      - libgit2
      - romkatv/powerlevel10k/powerlevel10k
    linux: []
  packages_from_source:
    - duf

dotfiles:
  repo: "https://github.com/mj-meyer/.dotfiles"
  branch: "master"

neovim:
  build_from_source: false
  directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
  build_dependencies:
    - autoconf
    - automake
    - cmake
    - curl
    - doxygen
    - g++
    - gettext
    - libtool
    - libtool-bin
    - ninja-build
    - pkg-config
    - unzip

golang:
  path: "{{ ansible_user_dir }}/.go"
  packages:
    - golang.org/x/tools/gopls@latest

nodejs:
  packages:
    - yarn

dockitems_disabled:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - Terminal
  - iBooks
  - iTunes

dockitems_enabled:
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 1
  - name: Alacritty
    path: "/Applications/Alacritty.app"
    pos: 2
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 3
  - name: Telegram
    path: "/Applications/Telegram.app"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5

darwin_hotkeys:
  # remap "show spotlight search` to `⌘ + g`
  64:
    parameters: "103, 5, 1048576"
    enabled: 1
  # disable "select the previous source in input menu"
  60:
    parameters: "32, 49, 262144"
    enabled: 0
  # remap "select the next source in input menu" to `⌘ + space`
  61:
    parameters: "32, 49, 1048576"
    enabled: 1
