---
- hosts: 127.0.0.1
  strategy: linear
  connection: local

  vars_files:
    - config.yaml

  roles:
    - name: common
      tags: common

    - name: oh-my-zsh
      tags: oh-my-zsh

    - name: dotfiles
      tags: dotfiles

    # - name: lunarvim      # Commented out - installing manually
    #   tags: lunarvim

    - name: tmux
      tags: tmux

    - name: system_defaults
      tags: system_defaults

    - name: node
      tags: node

    - name: aws
      tags: aws
