#!/usr/bin/env bash

set -euoE pipefail

# Installs the `share` CLI (https://github.com/mj-meyer/share.mjmeyer.dev) —
# publishes self-contained HTML to share.mjmeyer.dev and returns a link.
#
# The CLI runs on bare Node (>=23.6 native TypeScript stripping), so this does
# NOT run `npm install`. A consuming machine needs only the clone + the token.
#
# Requires git-over-SSH, so this must run AFTER the 1Password SSH-agent gate.

repo_url="${SHARE_REPO_URL:-git@github.com:mj-meyer/share.mjmeyer.dev.git}"
repo_dir="${SHARE_REPO_DIR:-$HOME/Personal/share.mjmeyer.dev}"
bin_dir="${SHARE_BIN_DIR:-$HOME/.local/bin}"
config_dir="$HOME/.config/share"
config_file="$config_dir/config"
# 1Password item holding the publish token (same value as the Worker's
# PUBLISH_TOKEN secret). Override with SHARE_OP_REF if the item moves.
op_ref="${SHARE_OP_REF:-op://Private/share.mjmeyer.dev/credential}"

min_node_major=23

clone_or_update_repo() {
  if [[ -d "$repo_dir/.git" ]]; then
    echo "⚪ [share] repo already present, fetching..."
    git -C "$repo_dir" pull --ff-only || echo "⚠️  [share] pull failed (local changes?) — leaving as-is."
  else
    echo "⚪ [share] cloning $repo_url..."
    mkdir -p "$(dirname "$repo_dir")"
    git clone "$repo_url" "$repo_dir"
  fi
}

check_node() {
  if ! command -v node &> /dev/null; then
    echo "❌ [share] node not found. Install Node >=${min_node_major}.6 (fnm) first."
    return 1
  fi
  local major
  major="$(node --version | sed 's/^v\([0-9]*\).*/\1/')"
  if (( major < min_node_major )); then
    echo "❌ [share] node v$major is too old — need >=${min_node_major}.6 for native TS stripping."
    return 1
  fi
  echo "⚪ [share] node $(node --version) ok."
}

link_binary() {
  mkdir -p "$bin_dir"
  # bin/share resolves symlinks to find its own repo root, so a plain symlink
  # is enough — and unlike `npm link` it does not live inside an fnm
  # version-specific directory that disappears on Node switch.
  ln -sfn "$repo_dir/bin/share" "$bin_dir/share"
  echo "⚪ [share] linked $bin_dir/share -> $repo_dir/bin/share"

  case ":$PATH:" in
    *":$bin_dir:"*) ;;
    *) echo "⚠️  [share] $bin_dir is not on your PATH — add it to your shell config." ;;
  esac
}

write_config() {
  if [[ -f "$config_file" ]] && grep -q '^[[:space:]]*SHARE_TOKEN=' "$config_file"; then
    echo "⚪ [share] config already has SHARE_TOKEN, leaving untouched."
    return 0
  fi

  if ! command -v op &> /dev/null; then
    echo "⚠️  [share] 1Password CLI (op) not found — cannot fetch the token."
    print_manual_config_help
    return 0
  fi

  echo "⚪ [share] reading publish token from 1Password ($op_ref)..."
  local token
  if ! token="$(op read "$op_ref" 2>/dev/null)" || [[ -z "$token" ]]; then
    echo "⚠️  [share] could not read $op_ref (not signed in, or item missing)."
    print_manual_config_help
    return 0
  fi

  mkdir -p "$config_dir"
  umask 077
  cat > "$config_file" <<EOF
# share CLI config — generated by scripts/common/install_share.sh
# Token comes from 1Password ($op_ref). Never commit this file.
SHARE_URL="https://share.mjmeyer.dev"
SHARE_TOKEN="$token"
EOF
  chmod 600 "$config_file"
  echo "⚪ [share] wrote $config_file (mode 600)."
}

print_manual_config_help() {
  cat <<EOF

   To finish setup by hand, create the 1Password item then re-run this script:

     Vault:  Private
     Item:   share.mjmeyer.dev   (type: API Credential)
     Field:  credential = <the PUBLISH_TOKEN you set as a Worker secret>

   Or write it directly:

     mkdir -p $config_dir
     printf 'SHARE_URL="https://share.mjmeyer.dev"\\nSHARE_TOKEN="…"\\n' > $config_file
     chmod 600 $config_file

EOF
}

verify() {
  # `share` with no args prints usage and exits 0.
  if "$bin_dir/share" > /dev/null 2>&1; then
    echo "✅ [share] installed. Try: share list"
  else
    echo "⚠️  [share] binary did not run cleanly — check $bin_dir/share"
  fi
}

install_share() {
  echo "⚪ [share] installing..."
  check_node
  clone_or_update_repo
  link_binary
  write_config
  verify
}

install_share
