- block:
    - name: Clone oh-my-zsh
      git:
        repo: "https://github.com/robbyrussell/oh-my-zsh.git"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"
        accept_hostkey: yes

    - name: Check if oh-my-zsh is installed
      stat:
        path: "{{ ansible_user_dir }}/.oh-my-zsh"
      register: omzsh

    - name: Install oh-my-zsh
      shell: "{{ ansible_user_dir }}/.oh-my-zsh/tools/install.sh"
      when: not omzsh.stat.exists

    - name: Install starship
      community.general.homebrew:
        name: starship
        state: present
      tags: homebrew

    - name: "Clone custom plugins"
      git:
        repo: "https://github.com/{{ item.repo }}"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
        accept_hostkey: yes
      with_items:
        - {
            name: "zsh-syntax-highlighting",
            repo: "zsh-users/zsh-syntax-highlighting.git",
          }
      # Note: 'git' plugin is built into oh-my-zsh, so we don't need to install it

  tags: oh-my-zsh_install
