---
- block:
    - include_tasks: set_osx_defaults.yaml
      loop: "{{ osx_global_defaults }}"
  tags:
    - defaults
    - global

- import_tasks: dock.yaml
  tags: dock
# - import_tasks: keybindings.yaml
#   tags: keybindings
